name: 构建纯IP形式的Derper服务器 to docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: modify
        run: |
          cd tailscale
          sed -i '/hi.ServerName != m.hostname/,+2d' cmd/derper/cert.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: icederce
          password: loveff.cxc.23
          
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
          
      - name: Generate current date
        id: time_id
        uses: Kaven-Universe/github-action-current-date-time@v1.1.0
        with:
          format: "YYYY-MM-DD"
          timezone-offset: 8
          
      - name: Docker meta
        id: docker_meta_id # you'll use this in the next step
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
             icederce/tailscale_pure_ip_derper
             ghcr.io/icederce/tailscale_pure_ip_derper
          # Docker tags based on the following events/attributes
          tags: |
            latest
            ${{ steps.time_id.outputs.day }}
          

      # Runs a single command using the runners shell
      - name: Build and push Docker images to docker.io and ghcr.io
        uses: docker/build-push-action@v2
        with:
          file: 'Dockerfile'
          platforms: linux/amd64,linux/arm/v8,linux/arm64
          context: ./
          push: true
          tags: ${{ steps.docker_meta_id.outputs.tags }}
          labels: ${{ steps.docker_meta_id.outputs.labels }}
